[phases.setup]
nixPkgs = ['nodejs_20', 'postgresql']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node db/migrate.js migrate && node dist/index.js'
